# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignuptest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signuptest(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1317, 741)
    self.driver.find_element(By.LINK_TEXT, "Signup").click()
    self.driver.find_element(By.ID, "id_username").send_keys("test_user_3")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("test_user_3@email.com")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("test_user3_fname")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("test_user3_lname")
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("testpwd3")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("testpwd3")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".row > .col-md-8").text == "Account created for test_user_3 !. You can now login.\\\\nLog In\\\\nUsername\\\\nPassword\\\\nDon\\\'t have an account? Sign up for FREE"
  
