# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeletepost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deletepost(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1317, 741)
    self.driver.find_element(By.LINK_TEXT, "test_user_3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) h3").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) h3")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.LINK_TEXT, "asdasd").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-trash-alt").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg").click()
    text = self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) > .card-body").text
    assert text != "test_user_3\\\\nasdasd\\\\nThis is Test Post\\\\nDecember 05 2020"
  
