# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatepost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createpost(self):
    self.driver.get("http://localhost:8000/")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Create New Post").click()
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").send_keys("asdasd")
    self.driver.find_element(By.ID, "id_content").click()
    self.driver.find_element(By.ID, "id_content").send_keys("This is Test Post")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".row > .col-md-8").text == "test_user_3\\\\nasdasd\\\\nThis is Test Post\\\\nCreated on : December 05 2020 Publish"
    self.driver.find_element(By.CSS_SELECTOR, ".card-body").click()
    self.driver.find_element(By.LINK_TEXT, "Publish").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "small:nth-child(1)").text == "Posted on : December 05 2020"
  
