# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUploadprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uploadprofile(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1317, 741)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "id_profilePic").click()
    self.driver.find_element(By.ID, "id_profilePic").send_keys(" ")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert").text == "Your acoount info is updated "
  
