# Generated by Django 3.0.4 on 2020-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200505_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roll_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
